<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4"/>
        <PackageReference Include="Microsoft.Extensions.Diagnostics.Abstractions" Version="10.0.10" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1"/>
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="Xunit.Combinatorial" Version="2.0.24" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.10" />
        <PackageReference Include="xunit.v3.assert" Version="3.2.2" />
        <PackageReference Include="xunit.v3.core" Version="3.2.2" />
        <PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\WindowsLocker.Core\WindowsLocker.Core.csproj" />      
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.Configuration">
        <HintPath>..\..\..\.nuget\packages\microsoft.extensions.configuration\10.0.10\lib\net10.0\Microsoft.Extensions.Configuration.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.Extensions.Configuration.Abstractions">
        <HintPath>..\..\..\.nuget\packages\microsoft.extensions.configuration.abstractions\10.0.10\lib\net10.0\Microsoft.Extensions.Configuration.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>